### ISSUE TITLE
Need to create guide for tick tokens 

### ISSUE THREAD

**Issue by spotlessmind1** [citizen-cosmos/SMM-Content#35]
From my script , please create video.

**Comment by spotlessmind1** [comment]
PLease check it with Danya. https://docs.google.com/document/d/1DkDEAsvCKK-m005XZ8oRFeucNWKS1AtFaqfYsnZkyGs/edit

**Comment by spotlessmind1** [comment]
I have updated text, added some slides in the begining and at the end. PLease check again all text.

**Comment by Cosmopusk** [comment]
in progress. I think we'll do it tonight
