### ISSUE TITLE
create video for Kadena

### ISSUE THREAD

**Issue by spotlessmind1** [citizen-cosmos/SMM-Content#48]

**Comment by spotlessmind1** [comment]
CReate video quotes for Kadena, video in "any" folder:

13:07 … 13:20 When people from the enterprise world come they are like - oh my god , enterprise blockchains, they gonna like destroy us and they trying to infiltrate into blockchain world and destroy everything from the inside.    (Serj)

14:05 … 14:20  Enterprise really doesn’t … 

33:54…34:04 Launching a new project on Ethereum is now super expensive! Someone like, you know, a kid can learn Ethereum and then go and deploy it on the main net. (Will)


49:09…. 50:00 Kadena itself …. We don’t move superfast, because it’s not Web2, it’s Web3. You can’t move fast and break things ’cause when you do you get hacked and it's a huge problems. (Will)

**Comment by Cosmopusk** [comment]
Done
