### ISSUE TITLE
video for orbital apes

### ISSUE THREAD

**Issue by spotlessmind1** [citizen-cosmos/SMM-Content#50]

**Comment by spotlessmind1** [comment]
Video at the folder - any 


9:48 …10:46 Why evmos... for us, we’ve always been big fans of the Cosmos ecosystem, the IBC. We think it’s amazing how everything is connected and how easy it is to move from one place to another. But our experience is in solidity and in EVM. So as soon as we saw EVMOS like this massive project EVM coming to IBC, we felt that was the right way for us to go   ... perfect for us.                     |  
 
31:07  .... 32:23 

we have been in crypto for long time... ...for the project. 

For the Co avatar please use - file Co avatar at the folder Any/ (as he recorded whithout web cam,)

**Comment by Cosmopusk** [comment]
Done
