### ISSUE TITLE
creates shorts with Cudos

### ISSUE THREAD

**Issue by spotlessmind1** [citizen-cosmos/SMM-Content#53]
I have uploaded video in folder "Any" 

Here quotes: 

11:24… 12:50  i am curious … efficiency a lot progress from our side  
Possible name or themes - (are you ready to install software on your computers? ) 

25:14 … 28:47  You mentioned … dns hosts  
Possible name or themes -  web 3 , web 2 , dns and relayers , what are risks…

**Comment by Cosmopusk** [comment]
ok, working for it...

**Comment by Cosmopusk** [comment]
Done
